#pragma once
#include <cstdint>

namespace mqtt{
    enum class PacketTypes: uint8_t{
        CONNECT = 1, // CLIENT TRIES TO CONNECT TO BROKER
        CONNACK = 2, // CONNECTION ACCEPTED
        PUBLISH = 3, // CLIENT PUBLISHES TO BROKER
        PUBACK = 4, // PUBLISH ACKNOWLEDGEMENT IF QoS LEVEL > 0
        PUBREC = 5, // PUBLISH RECEIEVED
        PUBREL = 6, // PUBLISH RELEASE FOR QoS LEVEL 2 AND STEP 2
        PUBCOMP = 7, // DELEVERY COMPLETED ACTUALLY HAPPENS IN QoS LEVEL 2 FINAL STEP
        SUBSCRIBE = 8, // CLIENT ASKS TO BROKER SEND THIS MESSAGE
        SUBACK = 9, // BROKER CONFIRMS THE SUBSCRIPTION
        UNSUBSCRIBE = 10, // CLIENT STOPS TO LISTEN TO TOPIC
        UNSUBACK = 11, // BROKER CONFIRMS THE UNSUBSCRIBE
        PINGREQ = 12, // CLIENT HEARTBEAT PING REQUEST ASKS THAT ARE YOU ALIVE?
        PINGRESP = 13, // BROKER REPLIES TO CLIENT THAT IT IS ALIVE
        DISCONNET = 14, // CLIENT LEAVES

    };

    enum class QoS: uint8_t{
        AT_MOST_ONCE = 0,
        AT_LEAST_ONCE = 1,
        EXACTLY_ONCE = 2
    };
}